include:
  - local: ".gitlab/release.yml"
  - local: ".gitlab/modules.yml"

stages:
  - build
  - release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/
  IMIN_VERSION: $CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  GPG_SIGNING_KEY: $GPG_SIGNING_KEY

services:
  - name: docker:20.10.12-dind
    command: ["--experimental"]