plugins {
    id 'idea'
    id 'io.github.ben-manes.versions' version '0.64.0'
    id 'com.vanniktech.maven.publish' version '0.37.0' apply false
    alias(libs.plugins.kotlin) apply false
    alias(libs.plugins.allure.gradle) apply false
}

wrapper { distributionType = Wrapper.DistributionType.BIN; gradleVersion = gradleWrapperVersion }

def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        isNonStable(it.candidate.version)
    }
}

subprojects {
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'io.qameta.allure'

    repositories { mavenCentral() }

    java {
        targetCompatibility = JavaVersion.VERSION_17
        sourceCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 17
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        compilerOptions {
            freeCompilerArgs.add('-Xjsr305=strict')
            freeCompilerArgs.add('-Xjdk-release=17')
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }

    tasks.withType(Test) {
        useJUnitPlatform()
        systemProperties["kotest.listener.spring.ignore.warning"] = true
        systemProperties['gradle.build.dir'] = layout.buildDirectory.get().asFile.absolutePath
    }

    dependencies {
        api 'org.jetbrains.kotlin:kotlin-reflect'
        api libs.awaitility
        api(libs.awaitility.kotlin) { transitive = false }
        api libs.kotest.assertions

        api libs.slf4j
        api libs.kotlin.logging
        runtimeOnly libs.logback

        testImplementation libs.mockk
        testImplementation libs.kotest.runner
        testImplementation(platform(libs.testcontainers))
    }
}
