ext.name = 'Selenide Page Object Framework'
ext.description = 'Framework based on Selenide provided convenient functional to create and manage your app Page Objects in automation testing'

apply from: "$rootDir/gradle/publishing.gradle"

test {
    systemProperty 'kotest.framework.config.fqn', 'org.brewcode.qa.pages.cfg.TestConfiguration'
}

dependencies {
    //// API ////
    api libs.geantyref
    api(libs.selenide) {
        exclude group: 'org.seleniumhq.selenium', module: 'selenium-ie-driver'
    }
    api(libs.allure.api) {
        exclude group: 'org.slf4j'
    }

    //// IMPL ////
    implementation(libs.allure) { transitive = false }

    testImplementation 'org.testcontainers:testcontainers'
}

allure {
    adapter {
        allureJavaVersion = libs.versions.allure.get()
        aspectjVersion = '1.9.25'
        aspectjWeaver = true

        frameworks { junit5 { enabled = false } }
    }
}
